language: node_js
addons:
  code_climate:
    repo_token: c807f544d0348ded936d1bba00c59941f47b8556dd3b227eb8c039a192f34644
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4.2'
before_script:
  - npm prune