language: node_js
addons:
  code_climate:
    repo_token: 573f6446506c45007300212c
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4.2'
before_script:
  - npm prune